# Generated by Django 2.1.5 on 2019-02-13 20:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratista', models.CharField(max_length=200, verbose_name='Razon social del Contratista')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Estudio')),
                ('fecha_de_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_de_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('tareas', ckeditor.fields.RichTextField(verbose_name='Tareas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
            },
        ),
        migrations.CreateModel(
            name='Promovete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promovente', models.CharField(max_length=200, verbose_name='Razon social del Promovente')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Contratista')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('fecha_de_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('tipo_de_proyecto', models.CharField(max_length=200, verbose_name='Tipo de proyecto')),
                ('contratistas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Contratista')),
                ('estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Estudios')),
                ('promoventes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Promovete')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyetos',
            },
        ),
    ]
