# Generated by Django 2.1.5 on 2019-02-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promovete',
            options={'verbose_name': 'Promovente', 'verbose_name_plural': 'Promoventes'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='estudios',
            name='tareas',
            field=models.TextField(verbose_name='Tareas'),
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='estudios',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='estudios',
            field=models.ManyToManyField(to='proyecto.Estudios'),
        ),
    ]
