# Generated by Django 2.1.5 on 2019-02-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20190213_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Tipo de Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='estudios',
            name='tipo',
            field=models.CharField(choices=[('mia', 'MIA'), ('etj', 'ETJ'), ('po', 'POEL'), ('poet', 'POET'), ('pdu', 'PDU'), ('pac', 'PACMUN'), ('scoo', 'SCOOPING'), ('scr', 'SCREENING')], default='mia', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estudios',
            field=models.ManyToManyField(to='proyecto.Estudios', verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo_de_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TiposProyectos'),
        ),
    ]
