# Generated by Django 2.1.5 on 2019-02-27 02:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0004_auto_20190213_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, verbose_name='Nombre o razon social del Cliente')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='Registro Federal de Contribuyentes')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('fecha_de_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_de_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('capacidad', models.TextField(max_length=500, verbose_name='Capacidad o descripcion del servicio')),
                ('tarea', ckeditor.fields.RichTextField(verbose_name='Tareas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Tipo de Proyecto')),
                ('desc', models.TextField(max_length=500, verbose_name='Descripcion del Proyecto')),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='TipoServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Tipo de Proyecto')),
                ('desc', ckeditor.fields.RichTextField(max_length=500, verbose_name='Descripcion del servicio')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='promovete',
            name='contratista',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='contratistas',
        ),
        migrations.AddField(
            model_name='promovete',
            name='representante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='promovete',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Registro Federal de Contribuyentes'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='auto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autorizacion del proyecto'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion del proyecto'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='superficie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Superficie del proyecto'),
        ),
        migrations.AlterField(
            model_name='promovete',
            name='promovente',
            field=models.CharField(max_length=200, verbose_name='Nombre o razon social del del Promovente'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estudios',
            field=models.ManyToManyField(to='proyecto.Servicios', verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='promoventes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Promovete', verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo_de_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TipoProyecto'),
        ),
        migrations.DeleteModel(
            name='Contratista',
        ),
        migrations.DeleteModel(
            name='Estudios',
        ),
        migrations.DeleteModel(
            name='TiposProyectos',
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipo_de_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TipoServicios', verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='promovente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Promovete', verbose_name='Promovente'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Cliente', verbose_name='Nombre del Cliente'),
        ),
    ]
