# Generated by Django 2.1.5 on 2019-03-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20190226_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='promoventes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Promovete', verbose_name='Nombre del Promovente'),
        ),
        migrations.AlterField(
            model_name='tiposervicios',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Tipo de servicio'),
        ),
    ]
