# Generated by Django 2.1.5 on 2019-03-11 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20190305_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-pk'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='promovete',
            options={'ordering': ['-pk'], 'verbose_name': 'Promovente', 'verbose_name_plural': 'Promoventes'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'ordering': ['-pk'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['-pk'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tipoproyecto',
            options={'ordering': ['-pk'], 'verbose_name': 'Tipo de Proyecto', 'verbose_name_plural': 'Tipos de Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicios',
            options={'ordering': ['-pk'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicios'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='promovente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Promovete', verbose_name='Promovente'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proyecto.Cliente', verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='promoventes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Promovete', verbose_name='Nombre del Promovente'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo_de_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.TipoProyecto'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tipo_de_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.TipoServicios', verbose_name='Tipo de Servicio'),
        ),
    ]
