# Generated by Django 2.1.5 on 2019-03-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200, verbose_name='Actividad')),
                ('desc', models.CharField(max_length=500, verbose_name='Descripcion del servicio')),
                ('img', models.ImageField(blank=True, null=True, upload_to='reporte', verbose_name='Evidencia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo del vehículo')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca del vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
