# Generated by Django 2.1.5 on 2019-03-05 01:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('inicio_jornada', models.TimeField(verbose_name='Inicio de jornada')),
                ('termino_jornada', models.TimeField(verbose_name='Termino de jornada')),
                ('servicio', models.CharField(choices=[('SUPERVISION', 'Supervision'), ('RESFLORA', 'Rescate de Flora'), ('RESFAUNA', 'Resctae de Fauna'), ('MANTENIMIENTO', 'Mantenimiento de Flora'), ('MONITOREO', 'Monitoreo')], default='SUPERVISION', max_length=20)),
                ('no_coordi', models.SmallIntegerField(verbose_name='numero de coordinadores')),
                ('no_especialistas', models.SmallIntegerField(verbose_name='numero de Especialistas')),
                ('no_tec', models.SmallIntegerField(verbose_name='numero de Técnicos')),
                ('desc', ckeditor.fields.RichTextField(max_length=5000, verbose_name='Descripcion del servicio')),
                ('img', models.ImageField(blank=True, null=True, upload_to='reporte', verbose_name='Evidencia')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.Actividad', verbose_name='Actividad a realizar')),
                ('coordinadores', models.ManyToManyField(related_name='Coordinadores', to=settings.AUTH_USER_MODEL, verbose_name='Coordinadores')),
                ('especialistas', models.ManyToManyField(related_name='Especialistas', to=settings.AUTH_USER_MODEL, verbose_name='Especialistas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable en sitio')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor de seguridad y ambiente')),
                ('tecnicos', models.ManyToManyField(related_name='Tecnicos', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos')),
            ],
        ),
    ]
