# Generated by Django 2.1.5 on 2019-03-05 19:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20190305_1202'),
        ('reporte', '0002_diario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diario',
            options={'verbose_name': 'Reporte diario', 'verbose_name_plural': 'Reportes Diarios'},
        ),
        migrations.AddField(
            model_name='diario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyectos', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Descripcion de la actividad'),
        ),
    ]
