# Generated by Django 2.1.5 on 2019-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_auto_20190305_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='modelos_vehiculos',
            field=models.ManyToManyField(blank=True, null=True, related_name='Modelo', to='reporte.Vehiculos', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='diario',
            name='no_vehiculo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='numero de vehículos'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='servicio',
            field=models.CharField(choices=[('Supervision', 'Supervision'), ('Rescate de Flora', 'Rescate de Flora'), ('Rescate de Fauna', 'Resctae de Fauna'), ('Mantenimiento de Flora', 'Mantenimiento de Flora'), ('Monitoreo', 'Monitoreo')], default='SUPERVISION', max_length=20),
        ),
    ]
